[package]
name = "llm_provider"
version = "0.1.0"
edition = "2024"

[dependencies.domain]
path = "../domain"

[dependencies]
async-trait = "0.1.91"
tokio-util = "0.7.19"

[dependencies.tokio]
version = "1.53.1"
features = ["full"]

[dependencies.serde]
version = "1.0.229"
features = ["derive"]


[dependencies.reqwest]
version = "0.13.4"
default-features = false
features = ["json"] 

